# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pytools.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pyTools(object):
    def setupUi(self, pyTools):
        pyTools.setObjectName("pyTools")
        pyTools.resize(634, 414)
        pyTools.setStyleSheet("QWidget {\n"
"    background-color:#FFFFFF;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(pyTools)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title = QtWidgets.QLabel(pyTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setStyleSheet("QLabel#title{\n"
"    font-size:18pt;\n"
"    border-top:none;\n"
"    border-left:none;\n"
"    border-right:none;\n"
"    border-bottom: 1px solid #000000;\n"
"    color: rgb(191, 165, 64);\n"
"}")
        self.title.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.title.setObjectName("title")
        self.gridLayout_2.addWidget(self.title, 0, 0, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(pyTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E8E8E8;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: #0E35F7;\n"
"}\n"
"QScrollArea {\n"
"    border-top : none; /*上框线*/\n"
"    border-bottom : none; /*下框线*/\n"
"    border-left : none; /*左框线*/\n"
"    border-right : 1px solid #000000; /*右框线*/\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 94, 371))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.conversionBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conversionBtn.sizePolicy().hasHeightForWidth())
        self.conversionBtn.setSizePolicy(sizePolicy)
        self.conversionBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.conversionBtn.setObjectName("conversionBtn")
        self.gridLayout.addWidget(self.conversionBtn, 1, 0, 1, 1)
        self.asciiBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asciiBtn.sizePolicy().hasHeightForWidth())
        self.asciiBtn.setSizePolicy(sizePolicy)
        self.asciiBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.asciiBtn.setObjectName("asciiBtn")
        self.gridLayout.addWidget(self.asciiBtn, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(pyTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.gridLayout_2.addWidget(self.stackedWidget, 1, 1, 1, 1)

        self.retranslateUi(pyTools)
        QtCore.QMetaObject.connectSlotsByName(pyTools)

    def retranslateUi(self, pyTools):
        _translate = QtCore.QCoreApplication.translate
        pyTools.setWindowTitle(_translate("pyTools", "Form"))
        self.title.setText(_translate("pyTools", "PY TOOLS"))
        self.conversionBtn.setText(_translate("pyTools", "CONCERSION"))
        self.asciiBtn.setText(_translate("pyTools", "ASCII"))
