name: test functions # 测试软件是否可以正常工作, 这里只是简单的测试会不会崩溃

on:
  push:
    branch:
    - develop

permissions:
  contents: read

jobs:
  test_software:
    name: test update software
    runs-on: windows-latest
    steps:
      - name: copy code
        uses: actions/checkout@v3 # 该action作用是将仓库代码拷贝到本地运行工作区
        with:
          ref: develop # copy develop分支, 不然默认是主分支
          submodules: recursive
      - name: download env
        uses: actions/setup-python@v4 # 设置python环境
        with: # 像这些action需要的参数, 类似于设备树, 遵循一定的字段规则
          python-version: "3.10" # 工程使用3.10版本python
          architecture: "x64"
          cache: 'pip'
      - name: download dependence
        run: | # 注意这里需要有对应的依赖目录, 可通过pip freeze > requirements.txt生成
          pip install -r requirements.txt
      - name: pack
        run: | # 首先需要对应ui文件转py, 然后调用打包工具生成对应的, 注意如果不加.\容易无法识别正确路径
          python .\ui_to_py.py 
          python .\pack.py
      - name: test running status
        uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: ./dist/py_tools.exe test
          contains: app run success
          expected_result: PASSED